### ISSUE TITLE
Add option for allow-ports

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-net#30]
### Description

Currently we apply TP on all ports by default and there's an option to disallow some ports (--inbound-disabled-ports/ --outbound-disabled-ports).

This issue is to add an option for disallowing all ports by default and only allowing some as opt-in.

**Comment by lukidzi** [comment]
Should we allow to define a combination of flags?

e.g:
```
      --inbound-disabled-ports: "1111,222"
      --inbound-enabled-ports: "3333,4444"
```

We could define `--inbound-disabled-ports: "none"` and` --inbound-enabled-ports: "all"` as default. I imagine that someone wants to redirect a few ports to mesh, exclude others and drop the rest. WDYT?
