### ISSUE TITLE
Investigate whether we need `--redirect-dns-upstream-target-chain`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-net#45]
### Description

This flag `--redirect-dns-upstream-target-chain string` is needed for tests only. Our guess is that we have other ways to make this work but we should double check it's the case.

If we really don't need it close this issue with the explanation.

**Comment by lukidzi** [comment]
It looks like it's not required anymore. Deprecated usage from Kuma and removed from tests https://github.com/kumahq/kuma/pull/4573

**Comment by lahabana** [comment]
Add log to say it's deprecated
